import pyvba
from typing import Any

XML = ...
JSON = ...

logger = ...


def timer(task: str) -> Any:
    def decorator(func) -> Any:
        def wrapper(*args, **kwargs) -> Any: ...


def cat_count(path: str) -> int: ...


def rm_empty_dirs(path: str): ...


class CATMiner:
    def __init__(self, in_dir: str, out_dir: str, file_type: int = 0, **kwargs):
        self.browser = ...

        self._in_dir = ...
        self._out_dir = ...
        self._tmp_dir = ...
        self._file_type = ...
        self._skip_ext = ...

        self._start_time = ...
        self._to_convert = ...
        self._file_num = ...
        self._pbar = ...

        self._kwargs = ...
        ...

    def begin(self) -> None: ...

    def _dir_crawl(self, in_dir: str, out_dir: str) -> None: ...

    def _cat_type(self, cat_file: str) -> pyvba.Browser: ...

    def _export_file(self, in_dir: str, out_dir: str) -> None: ...

    def _finish(self) -> None: ...
