import pyvba

def timer(func):
    def wrapper(*args, **kwargs): ...

def get_path(rel_path: str) -> str: ...

class CATMiner:
    def __init__(self, path: str = None, out_dir: str = None, *args, **kwargs):
        self.browser = None
        self._path = None
        self._out_dir = None
        ...
    def begin(self) -> None: ...
    def _update_log(self) -> None: ...
    def _dir_crawl(self) -> None: ...
    def _create_folder(self, name: str, path: str) -> None: ...
    def _open_zip(self, path: str) -> list: ...
    def _cat_type(self, cat_file_name: str) -> pyvba.Browser: ...
    def _export_file(self, path: str) -> None: ...
    def _finish(self) -> None: ...

