import pyvba
from typing import Any

XML = ...
JSON = ...

logger = ...


def timer(task: str) -> Any:
    def decorator(func) -> Any:
        def wrapper(*args, **kwargs) -> Any: ...


def cat_in_dir(path: str) -> bool:


class CATMiner:
    def __init__(self, path: str, out_dir: str, file_type: int = 0, **kwargs):
        self.browser = ...
        self._path = ...
        self._out_dir = ...
        self._tmp_dir = ...
        self._file_type = ...
        self._start_time = ...
        self._kwargs = ...
        ...

    def begin(self) -> None: ...

    def _dir_crawl(self, path: str, out_dir: str) -> None: ...

    def _cat_type(self, cat_file: str) -> pyvba.Browser: ...

    def _export_file(self, path: str, out_dir: str) -> None: ...

    def _finish(self) -> None: ...
