# This workflows will run all unittests using pytest and putest-cov
# For more information see: https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#testing-with-pytest-and-pytest-cov

name: Test Python Package

on:
  push

jobs:
  test:
    name: unittests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
